export default {
	EMBED_APP_URL: 'https://subhranshudas.github.io/embed-app',
	EMBED_VIEW_ROOT: 'EPNS_SDK_EMBED_VIEW_ROOT',
	STYLE_TAG_ID_PREFIX: 'STYLE_TAG_ID_',
	IFRAME_ID: 'EPNS_SDK_EMBED_IFRAME',
	CSS: {
		ZINDEX_MAX: 2147483638 // MAX value
	},
	IFRAME_TO_PARENT_MSG: 'IFRAME_TO_PARENT_MSG'
}